### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by tacotexmex** [IFRFSX/IceFlameMagicTexture#1]
Hi! I think something's weird here? 🤔 

![screenshot_20180310_202910](https://user-images.githubusercontent.com/25328789/37246018-d3072762-24a1-11e8-9463-aebf62e45401.png)

**Comment by IFRFSX** [comment]
Hello, I like cyan, so make it like that.

I've seen someone create a texture package called PixelBox from the Minetest forum, so it's changed. I will probably make a new version later.

Thank you for using this texture package, I will make more later! It is also possible to modify existing texture packages. You can send me an email. 1079092922 @qq.com
         --------------A minetest player from China. IFRFSX。

**Comment by tacotexmex** [comment]
I see, taste is personal. However as seen in this screenshot, dirt is both blue and brown at the same time which is incoherent:
![bild](https://user-images.githubusercontent.com/25328789/37255925-d6f86cfc-2553-11e8-9dd0-1cbcf349daf4.png)

Good to meet a chinese Minetester btw 🙂

**Comment by IFRFSX** [comment]
Thank you for your reminding, actually I knew this problem before, just because I think the problem is not changed. Since you are interested in this material package, I will change it. I'll remind you to download it.
Note: since I was busy building a map, I didn't have much time to make a texture package, so I changed the texture package on top of a Minetest Forum. I know that everyone in the use of free software and free culture license to distribute work, I choose WTFPL agreement in this material bag, in order to make PixelBox author can merge the texture and the contents of the package into the original.
谢谢您的提醒，其实我之前就知道这个问题，只是由于我觉得问题不大就没修改。既然您对这个材质包感兴趣，那么我就改改吧！改好了我会提醒您来下载。
注释：由于我忙着建地图，所以没多少时间造纹理包，于是我将一个 Minetest Forum上面的纹理包改了一下。我知道大家都在使用自由软件和自由文化许可证来发布作品，我在这个材质包里面选择WTFPL协议，是为了让PixelBox的作者能合并这个纹理包的内容进入原版。

**Comment by IFRFSX** [comment]
EMail:1079092922@qq.com
Mastodon:@IFRFSX

**Comment by IFRFSX** [comment]
hey,friend!


I have modified this texture package.

11 pictures have been updated.

I hope you like them.

**Comment by tacotexmex** [comment]
Nice work! See you in the forums. (It would be great with a chinese MT community there)
